- src/components/Layout/Header/index.tsx
- src/components/Layout/index.tsx
> fix(webapp): fix eslint errors

- .github/workflows/publish-prod.yaml
- utils/meta.mk
> ci(webapp): build and deploy workflow

- .github/workflows/publish-prod.yaml
- makefile
- utils/meta.mk
Adjust to action build deploy prod
Run the action
> Adjust to action build deploy

- .github/workflows/publish-prod.yaml
fix to action build deploy prod
fix the action to make build and push for deploy to prod
Run the action.
> fix(actions) fix to action build deploy prod

- .github/workflows/publish-prod.yaml
fix(actions): Rollback manual execution on action
Rollback manual execution on action publish release to production environment
Run the action
> fix(actions): Rollback manual execution on action

- .github/workflows/publish-prod.yaml
fix(actions): update version for loggin task in action
fix the warning in the action execution for use node 16
Run the action
2. next step
> fix(actions): update version for loggin task in action

- src/@types/context.ts
- src/@types/ual.ts
- src/components/Layout/Footer/index.tsx
- src/components/Vote/Body/index.tsx
- src/components/Voters/Body/index.tsx
- src/pages/styles.ts
-  remove commented code
1. first step
2. next step
> feat(webapp): remove commented code

- src/components/Layout/styles.ts
- Fit content for pages
1. first step
2. next step
> fix(webapp): Fit content for pages

- src/components/Layout/Container/index.tsx
- src/components/Layout/styles.ts
- Fix content layout min height
1. yarn dev
2. localhost:3000
> fix(webapp): fix content layout min height

- contracts/smartproxy/include/smartproxy.hpp
- contracts/smartproxy/src/smartproxy.cpp
- contracts/smartproxy/tests/tests.cpp
- if rank is 0 then 1
- MAX_EDEN_GROUP_SIZE = 6
- change from Fibonacci to `rank ? MAX_EDEN_GROUP_SIZE * rank : 1;`
> feat(contracts): update formula to calculate voter weight

- src/components/Home/Body/index.tsx
- src/components/Home/Body/styles.ts
- src/components/Home/Bottom/styles.ts
- src/components/LanguageSelector/styles.ts
- src/pages/styles.ts
- yarn.lock
- Add Styling for home page mobile version
1. first step
2. next step
> fix(webapp): home page mobile version

- src/components/SortComponent/styles.ts
- src/components/Vote/Head/index.tsx
- src/components/Vote/Head/styles.ts
- add header breakpoint for mobile
1. first step
2. next step
> fix(webapp): add header breakpoint for mobile

- src/components/Layout/index.tsx
- src/components/Layout/styles.ts
- src/components/Sidebar/index.tsx
- src/components/Sidebar/styles.ts
- remove sidebar build error
1. first step
2. next step
> fix(webapp): remove sidebar build error

- package.json
- src/components/Home/Body/index.tsx
- src/components/Layout/Footer/index.tsx
- src/components/Layout/Header/index.tsx
- src/components/Layout/index.tsx
- src/components/Vote/Body/index.tsx
- src/components/Voters/Body/index.tsx
- src/config/constants/bpjson.ts
- src/config/constants/index.ts
- src/config/constants/socialMediaLink.ts
- src/pages/about/index.tsx
- src/pages/about/styles.ts
- src/pages/vote/index.tsx
- src/utils/smart-proxy.ts
- yarn.lock
> feat(page): create about page

- package.json
- src/components/Layout/index.tsx
- tsconfig.json
- yarn.lock
-  resolve error related children node into _app.tsx
1. first step
2. next step
> fix(webapp): resolve error related children node into _app.tsx

- src/components/Vote/Body/index.tsx
- src/pages/vote/index.tsx
> fix(pages): vote user flow

- src/components/Vote/Body/index.tsx
- src/config/constants/socialMediaLink.ts
> fix(pages): vote section loading if user don't login

- src/components/SearchBar/index.tsx
- src/components/Voters/Body/index.tsx
- src/components/Voters/Head/index.tsx
- src/components/Voters/Head/styles.ts
- src/pages/voters/index.tsx
- Apply search function on voters page
https://user-images.githubusercontent.com/51149817/195179061-624f2b0b-5de1-433c-86b5-ccfa21fad35b.mp4
> Apply search function on voters page

- src/components/SearchBar/index.tsx
- src/components/Vote/Head/index.tsx
- src/components/Voters/Head/index.tsx
- src/pages/vote/index.tsx
- Resolve #60 
https://user-images.githubusercontent.com/51149817/195197141-ef80d533-ce56-4c9d-a168-51ec1da1d3aa.mp4
> Apply search function on vote page

- public/locales/en/common.json
- public/locales/es/common.json
- src/components/Home/Body/index.tsx
- src/components/LanguageSelector/index.tsx
- src/components/LanguageSelector/styles.ts
- src/components/Layout/Header/index.tsx
- src/components/Sidebar/index.tsx
- src/components/Voters/Body/index.tsx
- src/components/Voters/Head/index.tsx
- src/pages/about/index.tsx
- src/pages/index.tsx
- src/pages/vote/index.tsx
- src/pages/voters/index.tsx
-  implement i18n
1. first step
2. next step
> fix(webapp): implement i18n

- .gitignore
- contracts/smartproxy/src/smartproxy.cpp
> update smart contract messages

- contracts/smartproxy/src/smartproxy.cpp
- contracts/smartproxy/tests/tests.cpp
- Update unit test error messages
> perf(contract): update text errors in unit tests

- public/locales/en/common.json
- public/locales/es/common.json
- src/components/SortComponent/index.tsx
- src/components/SortComponent/styles.ts
- src/components/Vote/Body/index.tsx
- src/components/Vote/Head/index.tsx
- src/components/Vote/Head/styles.ts
- src/pages/vote/index.tsx
> feat(pages): apply sort function in vote page

- public/locales/en/common.json
- public/locales/es/common.json
- src/components/Layout/Header/index.tsx
- src/components/Vote/Body/index.tsx
- src/pages/vote/index.tsx
> feat(pages): apply validation delegate vote

- package.json
- src/components/Home/Bottom/index.tsx
- src/components/Home/Bottom/styles.ts
- src/components/Layout/index.tsx
- src/pages/styles.ts
- yarn.lock
- Resolve #68 
1. first step
2. next step
> fix(webapp): add twitter card

- src/components/Voters/Body/index.tsx
- src/pages/vote/index.tsx
> feat(pages): improve members loading data

- src/components/Voters/Body/index.tsx
> fix(pages): don't show inactive members

- src/components/AuthUAL/index.tsx
- src/components/AuthUAL/styles.ts
- Resolve #82 
1. first step
2. next step
> fix(webapp): remove wallet provider menu dropdown

- src/components/Voters/Body/index.tsx
> fix(webapp): rename vote weight text

- public/locales/en/common.json
- public/locales/es/common.json
- src/components/Layout/Header/index.tsx
- src/utils/eosio.ts
> feat(components): load total proxied votes

- README.md
> Update vote weight calculation

- src/components/Layout/Header/index.tsx
> fix(components): showed delegate button

- src/components/Vote/Head/index.tsx
- src/config/constants/footer.ts
- Resolve #105 
- Resolve #100
> feat(components): Add site links

- src/components/Home/Bottom/styles.ts
- src/components/Layout/Footer/index.tsx
- src/components/Layout/Footer/styles.ts
- src/utils/genesis-eden.ts
- Resolve #103 
- Resolve #117 
1. first step
2. next step
> fix(webapp): fix twitter card for mobile version and styling footer

- README.md
- contracts/smartproxy/include/smartproxy.hpp
- contracts/smartproxy/src/smartproxy.cpp
- contracts/smartproxy/tests/tests.cpp
- Update the Smart Contract voting weight formula
> perf(contract): update voting weight formula

- src/components/SortComponent/styles.ts
- src/components/Vote/Body/index.tsx
- src/components/Vote/Body/styles.ts
- src/pages/vote/index.tsx
- Resolve #119 
- Resolve #110
> Improved vote page interactions

- public/locales/en/common.json
- public/locales/es/common.json
- src/components/AuthUAL/index.tsx
- src/components/AuthUAL/useAuthUAL.hook.ts
- src/components/Home/Body/index.tsx
- src/components/Sidebar/index.tsx
- src/context/state.context.tsx
- src/utils/smart-proxy.ts
> fix(pages): validated eden menber login

- package.json
- src/components/AuthUAL/useAuthUAL.hook.ts
- src/components/Sidebar/index.tsx
- src/components/Sidebar/styles.ts
- yarn.lock
> feat(components): fixed sidebar breakpoints

- src/pages/about/index.tsx
> Update github link

- src/components/AuthUAL/index.tsx
- src/components/AuthUAL/styles.ts
- src/components/AuthUAL/useAuthUAL.hook.ts
- src/components/Home/Body/index.tsx
- src/components/Sidebar/index.tsx
- src/components/Vote/Body/index.tsx
- src/components/Vote/Head/index.tsx
- src/context/state.context.tsx
- src/pages/vote/index.tsx
- Resolve #136 
- Resolve #135
> fix(pages): Improved user login management

- next-i18next.config.js
- next.config.js
- Resolve locale language routes
1. first step
2. next step
> fix(webapp): resolve locale language routes

- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/ko/common.json
- src/components/AuthUAL/useAuthUAL.hook.ts
- src/components/Home/Body/index.tsx
- src/components/Sidebar/index.tsx
- src/context/state.context.tsx
> fix(homepage): add homepage button and improve user login state

- src/components/Layout/Footer/index.tsx
- src/components/Sidebar/index.tsx
- src/components/Sidebar/styles.ts
> feat(components): improved sidebar clicks interation

- src/config/constants/bpjson.ts
> feat(content): added bpjson content

- src/components/Layout/Footer/index.tsx
> Update footer text

- .github/workflows/publish-prod.yaml
> fix(voter): create proxy voter cron job script

- contracts/smartproxy/src/smartproxy.cpp
- Use right vector when voting for block producers
> fix(contracts): use right vector

- src/components/ImageLoad/index.tsx
- src/components/Voters/Body/index.tsx
> feat(components): improved spinner timer in imgLoading

- src/components/Voters/Body/index.tsx
- src/gql/voters.gql.ts
- rename members query
1. first step
2. next step
> fix(webapp): rename members query

- src/components/Voters/Body/index.tsx
- src/gql/voters.gql.ts
- Use correct value for election rank array
1. first step
2. next step
> fix(webapp): use correct value for election rank array

- src/components/Vote/Body/index.tsx
- src/pages/vote/index.tsx
> feat(pages): applied the selection to all bps by default

- public/locales/en/common.json
> content(public): updated en json

- src/gql/voters.gql.ts
> feat(components): improved search function

- src/components/Layout/Header/index.tsx
> fix(header): fixed some interactions

- src/config/constants/footer.ts
> feat(content): updated footer content and links

- src/components/Layout/Footer/index.tsx
> feat(components): updated footer content

- src/components/Vote/Body/index.tsx
- src/pages/vote/index.tsx
> feat(pages): added rank to bps info on vote page

- contracts/smartproxy/src/smartproxy.cpp
- Add require_auth( get_self ) validation to the clearall action
> fix(contracts): add require_auth in the clearall action

- src/utils/bps.ts
> fix(utils): changed way to get api data

- .github/workflows/publish-prod.yaml
fix(devops): change versions for deprecated issues
> fix(devops): change versions for deprecated issues

- .github/workflows/publish-prod.yaml
- Dockerfile
- makefile
- src/pages/vote/index.tsx
> feat(pages): added need validation on vote pages

- Dockerfile
- src/pages/vote/index.tsx
> feat(pages): commented eosrate integration

- src/components/Voters/Body/index.tsx
> fix(pages): fixed search response on voters page

- src/components/Voters/Body/index.tsx
> fix(webapp): added bps voted link

- k8s-dev/deployment.yml
- makefile
fix (devops): fix in makefile and number of replicas
> fix (devops): fix in makefile and number of replicas

- utils/meta.mk
fix (devops): fix on k8s folder find function
> fix (devops): fix on k8s folder find function

- .github/workflows/publish-dev.yaml
- .github/workflows/publish-prod.yaml
- src/config/graphqlConfig/index.ts
fix(webapp): change to variable the url for graphqlConfig
> fix(webapp): change to variable the url for graphqlConfig

- .github/workflows/publish-dev.yaml
fix(webapp): fix endpoit graphql dev
> fix(webapp): fix endpoit graphql dev

- src/config/graphqlConfig/index.ts
fix(webapp): fix code to url graphql dev
> fix(webapp): fix code to url graphql dev

- makefile
- src/components/Voters/Body/index.tsx
Fix url eden members and block explorer
> Fix url eden members and block explorer

- public/locales/cn/common.json
登录并给节点打分
maybe just
给节点打分
委托票权
>  Chinese Button Label Translation

- public/locales/cn/common.json
> fix(webapp): Chinese Button Label Translation

- src/components/Home/Bottom/index.tsx
>  add new tweet to homepage

- public/locales/en/common.json
> replace whitepaper for litepaper

- src/components/Home/Body/index.tsx
- src/components/Home/Bottom/styles.ts
- src/config/constants/homePage.ts
- [Improved homepage tweets styles](https://github.com/edenia/eden-smart-proxy/commit/7986bcf879d3d569fa73899823258388a01d1e35)
- [Changed logic litepaper button](https://github.com/edenia/eden-smart-proxy/commit/fbe434505588c3e6c61fd476ba6bdd12a8ea2c19)
> Changed logic litepaper button

- src/components/Home/Bottom/index.tsx
> fix add new tweet to homepage

- src/components/Home/Bottom/index.tsx
> fix(webapp): fix add new tweet to homepage

- package.json
- src/components/Home/Bottom/index.tsx
- src/components/Home/Bottom/styles.ts
- yarn.lock
- [Changed tweets components](https://github.com/edenia/eden-smart-proxy/commit/1d6bda261fbb4a8206a393d8524f57a35d2402f6)
> feat(pages): changed tweets components

- .env.example
- src/config/constants/footer.ts
> feat(components): updated telegram chanel link

- src/components/Voters/Body/index.tsx
> fix(pages): fixed telegram link on voters page

- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/ko/common.json
- src/components/DelegateButton/index.tsx
- src/components/LanguageSelector/index.tsx
- src/components/LanguageSelector/styles.ts
- src/components/Layout/Header/index.tsx
- src/components/Layout/Header/styles.ts
- src/components/Layout/styles.ts
- src/components/Sidebar/index.tsx
- src/components/Sidebar/styles.ts
- voter/src/index.js
> feat(components): added delegate button on mobile version

- src/pages/delegator/DelegatorActions.tsx
- src/pages/delegator/index.tsx
- Check i18n values
1. first step
2. next step
> fix: review i18n values

- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/ko/common.json
- src/pages/delegator/DelegatorActions.tsx
- src/pages/delegator/index.tsx
- signup trx
1. first step
2. next step
> fix: check logic to signup trx

- src/components/Sidebar/index.tsx
- Resolve About route sidebar issues
1. first step
2. next step
> fix: fix about route

- src/pages/delegator/DelegatorActions.tsx
- src/pages/delegator/index.tsx
- Actions and Format currency
1. first step
2. next step
> fix: i18n issue and test delegator actions

- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/ko/common.json
- src/components/AuthUAL/index.tsx
- src/components/CountdownTimer/index.tsx
- src/components/CountdownTimer/styles.ts
- src/components/Sidebar/index.tsx
- src/hooks/useCountdown/index.ts
- src/hooks/useUAL/index.tsx
- src/pages/delegator/DelegatorActions.tsx
- src/pages/delegator/styles.ts
- src/utils/smart-proxy.ts
- Resolve #271 
- Resolve #272 
- Resolve #273 
- Resolve #274 
- Resolve #275 
- Resolve #276 
1. run `yarn dev`
2. go to `localhost:3000`
> fix: fix issues related to delegator page
